### ISSUE TITLE
Can't start the scr-autopilot

### ISSUE THREAD

**Issue by BananaCakeComputer** [MaTY-MT/scr-autopilot#17]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77569325/178381685-5e7271e1-2e92-42fb-bc0b-e39c8818fa02.png">

Screen size 1920x1080

Windows 11

English

**Comment by MQXO** [comment]
You have to be in fullscreen, and while I'm unable to tell whether you're using large HUD it's worth giving that a check as to whether it's on.

**Comment by matrndev** [comment]
To confirm if the resolution and scaling is correct, go to Windows settings > Display (first option) > check if the settings are the same as in the screenshot below.
![image](https://user-images.githubusercontent.com/62469448/178522386-149358c4-81c7-4297-bd58-0aed0f8ba72f.png)

**Comment by BananaCakeComputer** [comment]
> To confirm if the resolution and scaling is correct, go to Windows settings > Display (first option) > check if the settings are the same as in the screenshot below. ![image](https://user-images.githubusercontent.com/62469448/178522386-149358c4-81c7-4297-bd58-0aed0f8ba72f.png)

![image](https://user-images.githubusercontent.com/77569325/178582238-9be4621a-539d-46c4-b4d7-9ed528a5f4d7.png)

![image](https://user-images.githubusercontent.com/77569325/178582464-6b89e69f-a73d-440c-8c01-9ed17847e23d.png)

![image](https://user-images.githubusercontent.com/77569325/178583560-203f965d-7db4-4bf0-a34b-f24ed2ce3ed2.png)

Still not working

**Comment by matrndev** [comment]
> > To confirm if the resolution and scaling is correct, go to Windows settings > Display (first option) > check if the settings are the same as in the screenshot below. ![image](https://user-images.githubusercontent.com/62469448/178522386-149358c4-81c7-4297-bd58-0aed0f8ba72f.png)
> 
> ![image](https://user-images.githubusercontent.com/77569325/178582238-9be4621a-539d-46c4-b4d7-9ed528a5f4d7.png)
> 
> ![image](https://user-images.githubusercontent.com/77569325/178582464-6b89e69f-a73d-440c-8c01-9ed17847e23d.png)
> 
> ![image](https://user-images.githubusercontent.com/77569325/178583560-203f965d-7db4-4bf0-a34b-f24ed2ce3ed2.png)
> 
> Still not working



As @AllisonNotBlack already stated, your Roblox client has to be set to fullscreen. Also, set your GUI in SCR to large.
